# Generated by Django 5.0.4 on 2024-05-04 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, verbose_name="organization name")),
                (
                    "developers",
                    models.ManyToManyField(related_name="organization_developers", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "managers",
                    models.ManyToManyField(related_name="organization_managers", to=settings.AUTH_USER_MODEL),
                ),
                ("owners", models.ManyToManyField(related_name="organization_owners", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("BACKLOG", "Backlog"), ("ACTIVE", "Active"), ("FUTURE", "Future")],
                        default="FUTURE",
                        max_length=255,
                        verbose_name="state of this sprint",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="organization sprint")),
                ("order_id", models.IntegerField(default=0, verbose_name="order of sprint to show")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_sprint",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, verbose_name="task name")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PEND", "Pend"),
                            ("TO_DEVELOP", "To Develop"),
                            ("DEVELOPING", "Developing"),
                            ("TO_REVIEW", "To Review"),
                            ("APPROVED", "Approved"),
                            ("TO_TEST", "To Test"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="TO_DEVELOP",
                        max_length=255,
                        verbose_name="state of this task",
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True, verbose_name="due date of task")),
                ("order_id", models.IntegerField(default=0, verbose_name="order of task to show")),
                (
                    "review_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_task",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_task",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprint_tasks",
                        to="organization.sprint",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
