# Generated by Django 5.0.4 on 2024-05-04 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="developers",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="organization_developers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="managers",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="organization_managers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="owners",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="organization_owners", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
